### ISSUE TITLE
Unbound module and Path is not in dune workspace after fresh and correct install on Windows

### ISSUE THREAD

**Issue by yankarinRG** [ocamllabs/vscode-ocaml-platform#532]
I am running _Windows 10 Pro 20H2 x64_ and using [Ocaml for Windows](https://fdopen.github.io/opam-repository-mingw/installation/) (v. 06. Feb 2021).
After installing _Ocaml for Windows_ (compiler version 4.11.1) I added `C:\OCaml64\usr\local\bin` and `C:\OCaml64\home\Omissis\.opam\4.11.1+mingw64c\bin` to `PATH` in the system environment variables, then installed the _OCaml Platform_ (v. 1.6.0) for Visual Studio and finally _OCaml-LSP_ (v. 1.4.0) with `opam install ocaml-lsp-server`

Here are the steps to follow to reproduce the annoying problem:
1. Open a _mintty_ shell
2. `cd` to a directory of your choice, for example `/cygdrive/c/Users/Omissis/Desktop/OCaml/`
3. create a new project with _dune_ (v. 2.8.2): `dune init project hello_world`
4. Open _Visual Studio Code_
5. Add the folder `hello_world` to Workspace and select the _4.11.1+mingw64c Global switch_ sandbox
6. Add `greeter.ml` in `lib` with the following content: `let message = "Hello, World!"`
7. replace the content of `bin/main.ml` with the following: `let () = print_endline Hello_world.Greeter.message`
8. The directory structure will be the following:
```
hello_world
│
├───bin
│       dune
│       main.ml
│
├───lib
│       dune
│       greeter.ml
│
└───test
        dune
        hello_world.ml
```
9. Issue `dune exec bin/main.exe`: **the executable will build correctly** and the output will be, as expected, _"Hello, World!"_
10. **Even though it correctly compiles and works**, _Visual Studio Code_ **will show the following** two **errors** in `main.ml`:
a) _"Unbound module Hello_world ocamllsp [1, 24]"_
```
{
	"resource": "/c:/Users/Omissis/Desktop/OCaml/hello_world/bin/main.ml",
	"owner": "_generated_diagnostic_collection_name_#2",
	"severity": 8,
	"message": "Unbound module Hello_world",
	"source": "ocamllsp",
	"startLineNumber": 1,
	"startColumn": 24,
	"endLineNumber": 1,
	"endColumn": 51
}
```
b) _"Path is not in dune workspace `c:/Users\Omissis\Desktop\OCaml\hello_world\bin` ocamllsp [2, 1]"_
```
{
	"resource": "/c:/Users/Omissis/Desktop/OCaml/hello_world/bin/main.ml",
	"owner": "_generated_diagnostic_collection_name_#2",
	"severity": 8,
	"message": "Path is not in dune workspace c:/Users\\Omissis\\Desktop\\OCaml\\hello_world\\bin",
	"source": "ocamllsp",
	"startLineNumber": 2,
	"startColumn": 1,
	"endLineNumber": 3,
	"endColumn": 1
}
```
11. ...and the following error in `greeter.ml`:
a) _"Path is not in dune workspace `c:/Users\Omissis\Desktop\OCaml\hello_world\lib` ocamllsp [2, 1]"_
```
{
	"resource": "/c:/Users/Omissis/Desktop/OCaml/hello_world/lib/greeter.ml",
	"owner": "_generated_diagnostic_collection_name_#2",
	"severity": 8,
	"message": "Path is not in dune workspace c:/Users\\Omissis\\Desktop\\OCaml\\hello_world\\lib",
	"source": "ocamllsp",
	"startLineNumber": 2,
	"startColumn": 1,
	"endLineNumber": 3,
	"endColumn": 1
}
```

**Comment by kkirstein** [comment]
I observe the same issue after upgrading dune to 2.8 (`opam pin add dune 2.7.1` is my temporary workaround).
Interestingly, using the same OCaml project on WSL2 (by vscode Remote-WSL) works fine. So I suspect an issue with windows 
 or cygwin paths that prevents the ocaml-platform or ocaml-lsp to find merlin data in the `_build` folder. Prior to dune 2.8 this info was stored in `.merlin` files within the source code folder(s).
I am not sure whether this is an issue of vscode-ocaml-platform or rather [ocaml-lsp-server](https://github.com/ocaml/ocaml-lsp). Could be related to https://github.com/ocaml/ocaml-lsp/issues/369.

**Comment by yankarinRG** [comment]
I downgraded dune in the only switch I have from 2.8.2 to 2.7.1 `using opam install dune.2.7.1` and I can't reproduce the issue, both errors are gone.
Thank you for the workaround! It was impossible to write code with all those errors and autocompletion not working.
Now with dune 2.7.1 the difference I observe is `.merlin` files in `lib `and `bin` subdirectories, so maybe as you said this is the issue: dune 2.8+ doesn't correctly generate or places these files in the subdirectories of the root project.

**Comment by voodoos** [comment]
Yes, there is a known issue with Dune 2.8 new configuration provider for Merlin on Windows.
It is already fixed on main and will be a part of patch release 2.8.3.
A fix will also be published on the Merlin side.

Sorry for the inconvenience. I will update this issue when both are released.

**Comment by yankarinRG** [comment]
The same exact issue happens as of Dune 2.8.4 and OCaml Platform 1.8.1.

**Comment by voodoos** [comment]
Yes, this issue also needs a fix in `ocaml-lsp-server` which is already on master but not released yet.

Meanwhile, it would be great if you could test it on your setting:

`opam pin add ocaml-lsp-server https://github.com/ocaml/ocaml-lsp.git`

**Comment by yankarinRG** [comment]
I can confirm that using the upstream version of OCaml-LSP fixes the errors.

**Comment by kkirstein** [comment]
Yes, I can also confirm that it works now:
`ocaml 4.11.1`
`dune 2.8.4`
`merlin 4.1-411`
`dot-merlin-reader 4.1`
`ocaml-lsp-server pinned to github.com/ocaml/ocaml-lsp.git`
`vscode-ocaml-platform 1.8.1`

Great work! Thanks!

**Comment by kkirstein** [comment]
Please note that `ocaml-lsp.git#master` now requires `ocaml 4.12.` I can confirm that it also works with `ocaml 4.12`.

**Comment by kkirstein** [comment]
A new release of `caml-lsp-server` is already pending.
For the impatient: `opam pin add ocaml-lsp-server https://github.com/ocaml/ocaml-lsp.git#1.5.0`

**Comment by kkirstein** [comment]
I think with the release of `ocaml-lsp-server 1.5.0` this issue is fixed. So, I suggest to close it.
