### ISSUE TITLE
Missing build artefacts in Open-VSX

### ISSUE THREAD

**Issue by voodoos** [ocamllabs/vscode-ocaml-platform#436]
I am using VSCodium on MacOS Big Sur.

The `vscode-ocaml-platform` extension stopped working in version 1.4.0.

I get the following message in the developer console:

```
/Applications/VSCodium.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:5407 Activating extension 'ocamllabs.ocaml-platform' failed: Cannot find module '~/.vscode-oss/extensions/ocamllabs.ocaml-platform-1.4.0/dist/vscode_ocaml_platform.js'
Require stack:
- /Applications/VSCodium.app/Contents/Resources/app/out/vs/loader.js
- /Applications/VSCodium.app/Contents/Resources/app/out/bootstrap-amd.js
- /Applications/VSCodium.app/Contents/Resources/app/out/bootstrap-fork.js.
_logMessageInConsole @ /Applications/VSCodium.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:5407
```

Looking at the designated `dist` directory : it only contains the `dune` file, no `vscode_ocaml_platform.js`.

I would be happy to provide more information if needed.

**Comment by mnxn** [comment]
It's not supposed to be missing. I don't get an error like that on my system.

If I download and uncompress the vsix directly from https://marketplace.visualstudio.com/_apis/public/gallery/publishers/ocamllabs/vsextensions/ocaml-platform/1.4.0/vspackage, `vscode_ocaml_platform.js` is included.

Have you tried reinstalling the extension? Maybe some other program deleted that file ... somehow.

**Comment by voodoos** [comment]
Yes I tried... the file appears to already be missing in the release zip on Github, is that normal ?

**Comment by mnxn** [comment]
Yes, the release zip is just the source code. `vscode_ocaml_platform.js` is built with `dune build @vscode` in the CI before the VSIX is uploaded to the vscode marketplace.

**Comment by voodoos** [comment]
Ok, I tried reinstalling via the marketplace on VSCodium and it failed (still empty dist dir).
However uninstalling and then installing manually with the `.vsix` worked.

This maybe related to the fact that I use VSCodium ?

**Comment by mnxn** [comment]
That's my guess. It might be because the JS file is a bit large (about 18 MB) and VSCodium can't extract it for some reason. I'll download VSCodium on my computer and see if I can reproduce.

**Comment by mnxn** [comment]
Just tried it on VSCodium on macOS Big Sur and `vscode_ocaml_platform.js` was indeed missing.

There's an open VSCodium issue (https://github.com/VSCodium/vscodium/issues/567) that talks about other extensions not working. I tried a few of the extensions listed there, and each extension had the same problem with certain files/folders missing when downloaded through the extensions panel.

I don't think there's anything we can do on our side, so I'm going to close this issue.

**Comment by voodoos** [comment]
I got this answer from Open-vsx: https://github.com/eclipse/openvsx/issues/203#issuecomment-728923939

> Thanks for reporting! This is probably not a problem with Open VSX itself, but rather the script used for publishing this particular extension, which is at https://github.com/open-vsx/publish-extensions. Please create an issue there.
> 
> The entry for this extension is here:
> https://github.com/open-vsx/publish-extensions/blob/97e2bad12da38f70feee26ea2af537c801413550/extensions.json#L923-L928
> 
> Maybe we're missing some build step before packaging the extension. The best solution would be to ask the original extension maintainers to publish to open-vsx.org themselves.

Is it new that the dist files are only built on CI and not committed to the repository ? That would explain the fact that the very basic configuration of this package in the Open VSX repository is not obtaining these built files anymore.

**Comment by mnxn** [comment]
> Is it new that the dist files are only built on CI and not committed to the repository?

It's not new, but what is new (since switching to js_of_ocaml) is that the extension builds with `dune build @vscode` and not `npm build`.

If Open VSX is just cloning the repo and packing the extension immediately, it won't be built correctly.

I notice some entries reference built VSIX files. We could start including the VSIX file as part of the releases if that service would use it.

**Comment by voodoos** [comment]
It looks like the VSIX path option is only for when prebuild command are used:
```
      // (OPTIONAL) Extra commands to run just before publishing to Open VSX (i.e. after "yarn/npm install", but before "vscode:prepublish")
      "prepublish": "npm run build",
       // (OPTIONAL) Relative path of the extension vsix file inside the git repo (i.e. when it is built by prepublish commands
       "extensionFile": "dist/js-debug.vsix"
```

However we can provide a direct link to the `vsix` file:
```
    {
      // Unique Open VSX extension ID in the form "<namespace>.<name>"
      "id": "rebornix.ruby",
      // A full URL from which to download the extension package
      "download": "https://github.com/rubyide/vscode-ruby/releases/download/v0.25.0/ruby-0.25.0.vsix",
      // (RECOMMENDED) The version that should be published; the script compares this version with the latest published version
      "version": "0.25.0"
    },
```

**Comment by mnxn** [comment]
I sent a PR: https://github.com/open-vsx/publish-extensions/pull/222

For the future, we should update the CI so it publishes to open-vsx in addition to the vscode marketplace.

**Comment by mnxn** [comment]
Open VSX has the correctly built version of the extension, so I'm going to close this issue now.
